version: "3.8"
services:
  db:
    image: postgres:13
    environment:
    - "POSTGRES_PASSWORD=mysecretpassword"
    - "POSTGRES_DB=study"
    - "POSTGRES_USER=rzstud"
    volumes:
    - studrz_db:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
  api:
    build: ../srv
    restart: always
    environment: 
    - "STUDRZ_DBPASSWORD=mysecretpassword"
    - "STUDRZ_DATABASE=study"
    - "STUDRZ_DBUSER=rzstud"
    - "STUDRZ_DBHOST=db"
    - "STUDRZ_DBPORT=5432"
    - "STUDRZ_DBSSL=false"
    - "STUDRZ_TIMEZONE=Europe/Berlin"
    - "STUDRZ_ADMINPASSWORD=start-123"
    # - "JAEGER_AGENT_HOST=deploy_jaeger-agent_1"
    # - "JAEGER_AGENT_PORT=6831"
    ports:
    - "42069:42069"
    links:
    - db
  ui:
    build: ../ui
    restart: always
    ports:
    - "3000:80"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  studrz_db:
